name: diego
version: 0.11.0
description: Helm chart for Diego components
type: application
apiVersion: v2
# renovate: dataSource=docker depName=diego-release packageName=ghcr.io/cloudfoundry/k8s/bbs
appVersion: 2.128.0
