auctioneer:
  enabled: false
  certificateSecret: ~
  hostname: "auctioneer.default.svc.cluster.local"
  image:
    repository: ghcr.io/cloudfoundry/k8s/auctioneer
    tag: ~
    imagePullPolicy: IfNotPresent
  nodeSelector: ~
  tolerations: ~

bbs:
  enabled: false
  certificateSecret: ~
  hostname: "bbs.default.svc.cluster.local"
  image:
    repository: ghcr.io/cloudfoundry/k8s/bbs
    tag: ~
    imagePullPolicy: IfNotPresent
  nodeSelector: ~
  tolerations: ~
  
fileserver:
  enabled: false
  hostname: "file-server.127-0-0-1.nip.io"
  image:
    repository: ghcr.io/cloudfoundry/k8s/fileserver
    # renovate: depName=cf-deployment image=ghcr.io/cloudfoundry/k8s/fileserver
    tag: "54.6.0"
    imagePullPolicy: IfNotPresent
  nodeSelector: ~
  tolerations: ~
  
locket:
  enabled: false
  certificateSecret: ~
  hostname: "locket.default.svc.cluster.local"
  image:
    repository: ghcr.io/cloudfoundry/k8s/locket
    tag: ~
    imagePullPolicy: IfNotPresent
  nodeSelector: ~
  tolerations: ~
  
sshProxy:
  enabled: false
  certificateSecret: ~
  hostname: "ssh-proxy.127-0-0-1.nip.io"
  image:
    repository: ghcr.io/cloudfoundry/k8s/ssh-proxy
    tag: ~
    imagePullPolicy: IfNotPresent
  nodeSelector: ~
  tolerations: ~
  
routeEmitter:
  enabled: false
  certificateSecret: ~
  natsAddress: "nats.default.svc.cluster.local:4222"
  locketAddress: "locket.default.svc.cluster.local:8891"
  bbsAddress: "https://bbs.default.svc.cluster.local:8889"
  image:
    repository: ghcr.io/cloudfoundry/k8s/route-emitter
    tag: ~
    imagePullPolicy: IfNotPresent
  nodeSelector:
    cloudfoundry.org/cell: "true"
  tolerations:
    - key: cloudfoundry.org/cell
      operator: Equal
      value: "true"
      effect: NoSchedule

dbPassword: ~
sshProxyHostKey: ~
diegoSSHCredentials: ~
oauthClientsSecret: ~
