name: loggregator
version: 0.5.1
description: Helm chart for Loggregator components
type: application
apiVersion: v2
# renovate: depName=loggregator-release image=ghcr.io/cloudfoundry/k8s/doppler
appVersion: 107.0.24
