{{ if .Values.cloudController.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cc-deployment-updater
  labels:
    app.kubernetes.io/name: cc-deployment-updater
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: cc-deployment-updater
  template:
    metadata:
      labels:
        app.kubernetes.io/name: cc-deployment-updater
    spec:
      containers:
        - name: cc-deployment-updater
          image: {{ .Values.cloudController.image.repository }}:{{ default .Chart.AppVersion .Values.cloudController.image.tag }}
          imagePullPolicy: {{ .Values.cloudController.image.imagePullPolicy }}
          command: ["bundle", "exec", "rake", "deployment_updater:start"]
          envFrom:
            - secretRef:
                name: cc-shared
          {{- if .Values.ccDeploymentUpdater.resources }}
          resources:
            {{- toYaml .Values.ccDeploymentUpdater.resources | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: cloud-controller
              mountPath: /etc/ssl/certs/cloud-controller
            - name: etc-cloud-controller
              mountPath: /etc/cloud-controller
            - name: tmpdir
              mountPath: /tmp
      {{- if .Values.ccDeploymentUpdater.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.ccDeploymentUpdater.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.ccDeploymentUpdater.tolerations }}
      tolerations:
        {{- toYaml .Values.ccDeploymentUpdater.tolerations | nindent 8 }}
      {{- end }}
      volumes:
        - name: cloud-controller
          secret:
            secretName: cloud-controller
        - name: etc-cloud-controller
          configMap:
            name: cloud-controller-configmap
        - name: tmpdir
          emptyDir: {}
{{ end }}