{{ if .Values.tpsWatcher.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tps-watcher-configmap
data:
  tps-watcher.json: |-
    {
      "bbs_client_cert": "/etc/ssl/certs/tps-watcher/tls.crt",
      "bbs_client_key": "/etc/ssl/certs/tps-watcher/tls.key",
      "bbs_ca_cert": "/etc/ssl/certs/tps-watcher/ca.crt",
      "bbs_api_url": "https://bbs.{{ .Release.Namespace }}.svc.cluster.local:8889",
      "cc_base_url": "https://cloud-controller.{{ .Release.Namespace }}.svc.cluster.local:9023",
      "cc_client_cert": "/etc/ssl/certs/tps-watcher/tls.crt",
      "cc_client_key": "/etc/ssl/certs/tps-watcher/tls.key",
      "cc_ca_cert": "/etc/ssl/certs/tps-watcher/ca.crt",
      "debug_server_config": {
        "debug_address": "127.0.0.1:17015"
      },
      "dropsonde_port": 3457,
      "lager_config": {
        "log_level": "info",
        "time_format": "rfc3339"
      },
      "locket_client_cert_file": "/etc/ssl/certs/tps-watcher/tls.crt",
      "locket_client_key_file": "/etc/ssl/certs/tps-watcher/tls.key",
      "locket_ca_cert_file": "/etc/ssl/certs/tps-watcher/ca.crt",
      "locket_address": "locket.{{ .Release.Namespace }}.svc.cluster.local:8891",
      "instance_id": "62bcb8b5-ee8a-4dd9-bec0-3788beb13855"
    }
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: tps-watcher
  labels:
    app: tps-watcher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tps-watcher
  template:
    metadata:
      labels:
        app: tps-watcher
    spec:
      containers:
        - name: tps-watcher
          image: {{ .Values.tpsWatcher.image.repository }}:{{ default .Chart.AppVersion .Values.tpsWatcher.image.tag }}
          imagePullPolicy: {{ .Values.tpsWatcher.image.imagePullPolicy }}
          {{- if .Values.tpsWatcher.resources }}
          resources:
            {{- toYaml .Values.tpsWatcher.resources | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: tps-watcher
              mountPath: /etc/ssl/certs/tps-watcher
            - name: tps-watcher-config
              mountPath: /tps-watcher
            - name: tmp
              mountPath: /tmp
      {{- if .Values.tpsWatcher.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.tpsWatcher.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.tpsWatcher.tolerations }}
      tolerations:
        {{- toYaml .Values.tpsWatcher.tolerations | nindent 8 }}
      {{- end }}
      volumes:
        - name: tmp
          emptyDir: {}
        - name: tps-watcher
          secret:
            secretName: {{ default "tps-watcher" .Values.tpsWatcher.certificateSecret }}
        - name: tps-watcher-config
          configMap:
            name: tps-watcher-configmap
{{ if not .Values.tpsWatcher.certificateSecret }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tps-watcher
  namespace: default
spec:
  secretName: tps-watcher
  commonName: tps-watcher
  dnsNames:
    - tps
    - tps.{{ .Release.Namespace }}.svc
    - tps.{{ .Release.Namespace }}.svc.cluster.local
    - "{{ .Values.tpsWatcher.hostname }}"
  issuerRef:
    name: ca-issuer
    kind: ClusterIssuer
  usages:
    - key encipherment
    - digital signature
    - server auth
    - client auth
  privateKey:
    rotationPolicy: Always
{{- end }}
{{- end }}
