{{- if .Values.boshDnsAdapter.enabled }}
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: bosh-dns
  labels:
    app: bosh-dns
  annotations:
    checksum/config: {{ include (print $.Template.BasePath "/bosh-dns-configmap.yaml") . | sha256sum }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bosh-dns
  template:
    metadata:
      labels:
        app: bosh-dns
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/bosh-dns-configmap.yaml") . | sha256sum }}
    spec:
      containers:
        - name: bosh-dns-adapter
          image: {{ .Values.boshDnsAdapter.image.repository }}:{{ default .Chart.AppVersion .Values.boshDnsAdapter.image.tag }}
          imagePullPolicy: {{ .Values.boshDnsAdapter.image.imagePullPolicy }}
          {{- if .Values.boshDnsAdapter.resources }}
          resources:
            {{- toYaml .Values.boshDnsAdapter.resources | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: bosh-dns-adapter
              mountPath: /etc/ssl/certs/bosh-dns-adapter
            - name: bosh-dns-config
              mountPath: /bosh-dns-adapter/bosh-dns-adapter.json
              subPath: bosh-dns-adapter.json
        - name: bosh-dns
          image: {{ .Values.boshDns.image.repository }}:{{ .Values.boshDns.image.tag }}
          imagePullPolicy: {{ .Values.boshDns.image.imagePullPolicy }}
          {{- if .Values.boshDns.resources }}
          resources:
            {{- toYaml .Values.boshDns.resources | nindent 12 }}
          {{- end }}
          ports:
            - containerPort: 53
              name: tcp
              protocol: TCP
            - containerPort: 53
              name: udp
              protocol: UDP
          volumeMounts:
            - name: bosh-dns
              mountPath: /etc/ssl/certs/bosh-dns
            - name: bosh-dns-config
              mountPath: /bosh-dns/bosh-dns.json
              subPath: bosh-dns.json
            - name: bosh-dns-config
              mountPath: /bosh-dns/handlers.json
              subPath: handlers.json
            - name: bosh-dns-config
              mountPath: /bosh-dns/records.json
              subPath: records.json
      {{- if .Values.boshDns.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.boshDns.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.boshDns.tolerations }}
      tolerations:
        {{- toYaml .Values.boshDns.tolerations | nindent 8 }}
      {{- end }}
      volumes:
        - name: bosh-dns-adapter
          secret:
            secretName: {{ default "bosh-dns-adapter" .Values.boshDnsAdapter.certificateSecret }}
        - name: bosh-dns
          secret:
            secretName: {{ default "bosh-dns" .Values.boshDns.certificateSecret }}
        - name: bosh-dns-config
          configMap:
            name: bosh-dns-configmap
---
kind: Service
apiVersion: v1
metadata:
  name: bosh-dns
  labels:
    app: bosh-dns
spec:
  ports:
    - port: 53
      targetPort: 53
      name: tcp
      protocol: TCP
    - port: 53
      targetPort: 53
      name: udp
      protocol: UDP
  selector:
    app: bosh-dns
{{ if not .Values.boshDnsAdapter.certificateSecret }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: bosh-dns-adapter
spec:
  secretName: bosh-dns-adapter
  commonName: bosh-dns-adapter
  dnsNames:
    - bosh-dns-adapter
    - bosh-dns-adapter.{{ .Release.Namespace }}.svc
    - bosh-dns-adapter.{{ .Release.Namespace }}.svc.cluster.local
  issuerRef:
    name: ca-issuer
    kind: ClusterIssuer
  usages:
    - key encipherment
    - digital signature
    - server auth
    - client auth
  privateKey:
    rotationPolicy: Always
{{end }}
{{- if not .Values.boshDns.certificateSecret }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: bosh-dns
spec:
  secretName: bosh-dns
  commonName: bosh-dns
  dnsNames:
    - bosh-dns
    - bosh-dns.{{ .Release.Namespace }}.svc
    - bosh-dns.{{ .Release.Namespace }}.svc.cluster.local
  issuerRef:
    name: ca-issuer
    kind: ClusterIssuer
  usages:
    - key encipherment
    - digital signature
    - server auth
    - client auth
  privateKey:
    rotationPolicy: Always
{{end }}
{{- end }}