{{- if .Values.policyServer.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: policy-server-configmap
data:
  policy-server.json: |-
    {
      "listen_host": "0.0.0.0",
      "listen_port": 4002,
      "log_prefix": "cfnetworking",
      "debug_server_host": "127.0.0.1",
      "enable_tls": false,
      "ca_cert_file": "/etc/ssl/certs/policy-server/ca.crt",
      "server_cert_file": "/etc/ssl/certs/policy-server/tls.crt",
      "server_key_file": "/etc/ssl/certs/policy-server/tls.key",
      "debug_server_port": 31821,
      "uaa_client": "network-policy",
      "uaa_client_secret": {{ .Values.policyServer.oauthClientsSecret | quote }},
      "uaa_url": "https://uaa.{{ .Release.Namespace }}.svc.cluster.local",
      "uaa_port": 443,
      "cc_url": "https://cloud-controller.{{ .Release.Namespace }}.svc.cluster.local:9024",
      "cc_ca_cert": "/etc/ssl/certs/policy-server/ca.crt",
      "skip_ssl_validation": false,
      "database": {
        "type": "postgres",
        "user": "postgres",
        "password": "{{ .Values.policyServer.dbPassword }}",
        "host": "postgresql",
        "port": 5432,
        "timeout": 120,
        "database_name": "network_policy",
        "require_ssl": true,
        "ca_cert": "/etc/ssl/certs/policy-server/ca.crt",
        "skip_hostname_validation": false
      },
      "database_migration_timeout": 600,
      "max_idle_connections": 10,
      "max_open_connections": 200,
      "connections_max_lifetime_seconds": 3600,
      "tag_length": 2,
      "metron_address": "forwarder-agent.{{ .Release.Namespace }}.svc.cluster.local:3458",
      "log_level": "info",
      "cleanup_interval": 3600,
      "max_policies": 150,
      "enable_space_developer_self_service": true,
      "allowed_cors_domains": [],
      "uaa_ca": "/etc/ssl/certs/policy-server/ca.crt",
      "request_timeout": 5
    }
  policy-server-internal.json: |-
    {
      "listen_host": "0.0.0.0",
      "log_prefix": "cfnetworking",
      "debug_server_host": "127.0.0.1",
      "debug_server_port": 31945,
      "health_check_port": 31946,
      "internal_listen_port": 4003,
      "database": {
        "type": "postgres",
        "user": "postgres",
        "password": "{{ .Values.policyServer.dbPassword }}",
        "host": "postgresql",
        "port": 5432,
        "timeout": 120,
        "database_name": "network_policy",
        "require_ssl": true,
        "ca_cert": "/etc/ssl/certs/policy-server/ca.crt",
        "skip_hostname_validation": false
      },
      "max_idle_connections": 10,
      "max_open_connections": 200,
      "connections_max_lifetime_seconds": 3600,
      "tag_length": 2,
      "metron_address": "forwarder-agent.{{ .Release.Namespace }}.svc.cluster.local:3458",
      "log_level": "debug",
      "ca_cert_file": "/etc/ssl/certs/policy-server/ca.crt",
      "server_cert_file": "/etc/ssl/certs/policy-server/tls.crt",
      "server_key_file": "/etc/ssl/certs/policy-server/tls.key",
      "request_timeout": 5
      }
  policy-server-asg-syncer.json: |-
    {
      "uuid": "07c65e06-b676-4f4a-a37f-96df62d387d7",
      "database": {
          "type": "postgres",
          "user": "postgres",
          "password": "{{ .Values.policyServer.dbPassword }}",
          "host": "postgresql",
          "port": 5432,
          "timeout": 120,
          "database_name": "network_policy",
          "require_ssl": true,
          "ca_cert": "/etc/ssl/certs/policy-server/ca.crt",
          "skip_hostname_validation": false
      },
      "uaa_client": "network-policy",
      "uaa_client_secret": {{ .Values.policyServer.oauthClientsSecret | quote }},
      "uaa_url": "https://uaa.{{ .Release.Namespace }}.svc.cluster.local",
      "uaa_port": 443,
      "uaa_ca": "/etc/ssl/certs/policy-server/ca.crt",
      "cc_url": "https://cloud-controller.{{ .Release.Namespace }}.svc.cluster.local:9024",
      "cc_ca_cert": "/etc/ssl/certs/policy-server/ca.crt",
      "cc_internal_url": "https://cloud-controller.{{ .Release.Namespace }}.svc.cluster.local:9023",
      "cc_internal_ca_cert": "/etc/ssl/certs/policy-server/ca.crt",
      "cc_internal_client_cert": "/etc/ssl/certs/policy-server/tls.crt",
      "cc_internal_client_key": "/etc/ssl/certs/policy-server/tls.key",
      "log_prefix": "cfnetworking",
      "log_level": "debug",
      "metron_address": "forwarder-agent.{{ .Release.Namespace }}.svc.cluster.local:3458",
      "skip_ssl_validation": false,
      "asg_poll_interval_seconds": 60,
      "retry_deadline_seconds": 300,
      "locket_address": "locket.{{ .Release.Namespace }}.svc.cluster.local:8891",
      "locket_ca_cert_file": "/etc/ssl/certs/policy-server/ca.crt",
      "locket_client_cert_file": "/etc/ssl/certs/policy-server/tls.crt",
      "locket_client_key_file": "/etc/ssl/certs/policy-server/tls.key"
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: policy-server-route-registrar-configmap
data:
  route-registrar.json: |-
    {
      "message_bus_servers": [
        {
          "host": "nats.{{ .Release.Namespace }}.svc.cluster.local:4222"
        }
      ],
      "nats_mtls_config": {
        "enabled": true,
        "cert_path": "/etc/ssl/certs/policy-server/tls.crt",
        "key_path": "/etc/ssl/certs/policy-server/tls.key",
        "ca_path": "/etc/ssl/certs/policy-server/ca.crt"
      },
      "host": "",
      "routes": [
        {
          "name": "policy-server",
          "port": 4002,
          "registration_interval": "10s",
          "server_cert_domain_san": "{{ .Values.policyServer.externalDomain }}",
          "uris": [
            "{{ .Values.policyServer.externalDomain }}/networking"
          ]
        }
      ]
    }
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: policy-server
  labels:
    app: policy-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: policy-server
  template:
    metadata:
      labels:
        app: policy-server
    spec:
      containers:
        - name: policy-server
          image: {{ .Values.policyServer.image.repository }}:{{ default .Chart.AppVersion .Values.policyServer.image.tag }}
          imagePullPolicy: {{ .Values.policyServer.image.imagePullPolicy }}
          command: [ "/usr/local/bin/policy-server" ]
          args:
          - -config-file
          - /policy-server/policy-server.json
          volumeMounts:
            - name: policy-server-config
              mountPath: /policy-server
            - name: policy-server
              mountPath: /etc/ssl/certs/policy-server
              readOnly: true
          {{- if .Values.policyServer.resources }}
          resources:
            {{- toYaml .Values.policyServer.resources | nindent 12 }}
          {{- end }}
        - name: policy-server-internal
          image: {{ .Values.policyServer.image.repository }}:{{ default .Chart.AppVersion .Values.policyServer.image.tag }}
          imagePullPolicy: {{ .Values.policyServer.image.imagePullPolicy }}
          command: [ "/usr/local/bin/policy-server-internal" ]
          args:
          - -config-file
          - /policy-server/policy-server-internal.json
          volumeMounts:
            - name: policy-server-config
              mountPath: /policy-server
            - name: policy-server
              mountPath: /etc/ssl/certs/policy-server
              readOnly: true
          {{- if .Values.policyServer.resources }}
          resources:
            {{- toYaml .Values.policyServer.resources | nindent 12 }}
          {{- end }}
        - name: asg-syncer
          image: {{ .Values.policyServer.image.repository }}:{{ default .Chart.AppVersion .Values.policyServer.image.tag }}
          imagePullPolicy: {{ .Values.policyServer.image.imagePullPolicy }}
          command: [ "/usr/local/bin/policy-server-asg-syncer" ]
          args:
          - -config-file
          - /policy-server/policy-server-asg-syncer.json
          volumeMounts:
            - name: policy-server-config
              mountPath: /policy-server
            - name: policy-server
              mountPath: /etc/ssl/certs/policy-server
              readOnly: true
          {{- if .Values.policyServer.resources }}
          resources:
            {{- toYaml .Values.policyServer.resources | nindent 12 }}
          {{- end }}
        - name: route-registrar
          image: {{ .Values.routeRegistrar.image.repository }}:{{ .Values.routeRegistrar.image.tag }}
          imagePullPolicy: {{ .Values.routeRegistrar.image.imagePullPolicy }}
          env:
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          {{- if .Values.routeRegistrar.resources }}
          resources:
            {{- toYaml .Values.routeRegistrar.resources | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: policy-server
              mountPath: /etc/ssl/certs/policy-server
            - name: etc-route-registrar
              mountPath: /etc/route-registrar-template
            - name: tmpdir
              mountPath: /tmp
      {{- if .Values.policyServer.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.policyServer.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.policyServer.tolerations }}
      tolerations:
        {{- toYaml .Values.policyServer.tolerations | nindent 8 }}
      {{- end }}
      volumes:
        - name: policy-server-config
          configMap:
            name: policy-server-configmap
        - name: policy-server
          secret:
            secretName: {{ default "policy-server" .Values.policyServer.certificateSecret }}
        - name: etc-route-registrar
          configMap:
            name: policy-server-route-registrar-configmap
        - name: tmpdir
          emptyDir: {}
---
kind: Service
apiVersion: v1
metadata:
  name: policy-server
  labels:
    app: policy-server
spec:
  ports:
  - port: 4003
    name: https
    targetPort: 4003
    appProtocol: kubernetes.io/h2c
  selector:
    app: policy-server
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TCPRoute
metadata:
  name: policy-server
spec:
  parentRefs:
    - name: istio-gateway
      sectionName: policy-server
  rules:
    - backendRefs:
        - name: policy-server
          port: 4003
---
{{- if not .Values.policyServer.certificateSecret }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: policy-server
spec:
  secretName: policy-server
  commonName: client
  dnsNames:
    - policy-server
    - policy-server.{{ .Release.Namespace }}.svc
    - policy-server.{{ .Release.Namespace }}.svc.cluster.local
    - "{{ .Values.policyServer.hostname }}"
  issuerRef:
    name: ca-issuer
    kind: ClusterIssuer
  usages:
    - key encipherment
    - digital signature
    - server auth
    - client auth
  privateKey:
    rotationPolicy: Always
{{- end }}
{{- end }}
