name: uaa
version: 0.11.0
description: A Helm chart for UAA
type: application
apiVersion: v2
# renovate: dataSource=docker depName=uaa-release packageName=ghcr.io/cloudfoundry/k8s/uaa
appVersion: 78.7.0
