name: credhub
version: 0.8.0
description: Helm chart for CredHub components
type: application
apiVersion: v2
# renovate: dataSource=docker depName=credhub-release packageName=europe-west3-docker.pkg.dev/sap-se-gcp-istio-dev/public/cf/credhub
appVersion: 2.14.17
