hostname: "credhub.127-0-0-1.nip.io"
uaa:
  address: "https://uaa.127-0-0-1.nip.io"

image:
  repository: ghcr.io/cloudfoundry/k8s/credhub
  tag: ""
  imagePullPolicy: IfNotPresent

nodeSelector: ~
tolerations: ~

dbPassword: ~

# Credhub security configuration
# If not provided, secure random values will be generated
credhub:
  encryptionPassword: ~  # 32-char random generated if not set
  trustStorePassword: ~  # defaults to "changeit" if not set
  keyStorePassword: ~    # defaults to "changeit" if not set
  keyPassword: ~         # defaults to "changeit" if not set

caCertificateSecret: root-ca
