hostname: "credhub.127-0-0-1.nip.io"
uaa:
  address: "https://uaa.127-0-0-1.nip.io"

image:
  repository: ghcr.io/cloudfoundry/k8s/credhub
  tag: ""
  imagePullPolicy: IfNotPresent

nodeSelector: ~
tolerations: ~

dbPassword: ~

caCertificateSecret: root-ca
