{{- if .Values.fileserver.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fileserver-configmap
data:
  nginx.conf: |-
    {{- tpl (.Files.Get "fileserver/nginx.conf") . | nindent 4 }}
---
kind: Service
apiVersion: v1
metadata:
  name: file-server
  labels:
    app.kubernetes.io/name: file-server
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app.kubernetes.io/name: file-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-server
  labels:
    app.kubernetes.io/name: file-server
spec:
  # This is a singleton.
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: file-server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: file-server
    spec:
      containers:
        - name: nginx
          image: {{ .Values.fileserver.image.repository }}:{{ default .Values.fileserver.version .Values.fileserver.image.tag }}
          imagePullPolicy: {{ .Values.fileserver.image.imagePullPolicy }}
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
          {{- if .Values.fileserver.resources }}
          resources:
            {{- toYaml .Values.fileserver.resources | nindent 12 }}
          {{- end }}
      {{- if .Values.fileserver.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.fileserver.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.fileserver.tolerations }}
      tolerations:
        {{- toYaml .Values.fileserver.tolerations | nindent 8 }}
      {{- end }}
      volumes:
        - name: nginx-config
          configMap:
            name: fileserver-configmap
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: file-server
spec:
  parentRefs:
    - name: istio-gateway
  hostnames:
    - "{{ .Values.fileserver.hostname }}"
  rules:
    - backendRefs:
        - name: file-server
          port: 8080
{{- end }}