{{- if .Values.routeEmitter.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: route-emitter
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: route-emitter
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: route-emitter
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: route-emitter
subjects:
- kind: ServiceAccount
  name: route-emitter
  namespace: default
---
kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: route-emitter
  labels:
    app: route-emitter
  annotations:
    checksum/config: {{ include (print $.Template.BasePath "/route-emitter-configmap.yaml") . | sha256sum }}
spec:
  selector:
    matchLabels:
      app: route-emitter
  template:
    metadata:
      labels:
        app: route-emitter
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/route-emitter-configmap.yaml") . | sha256sum }}
    spec:
      serviceAccountName: route-emitter
      initContainers:
        - name: route-emitter-init
          image: bitnami/kubectl:latest
          imagePullPolicy: IfNotPresent
          command:
            - sh
            - -c
            - |
              NODE_UID=$(kubectl get node $NODE_NAME -o jsonpath='{.metadata.uid}')
              export NODE_UID
              cat /route-emitter/route-emitter.json | envsubst > /tmp/route-emitter.json
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: route-emitter-config
              mountPath: /route-emitter
            - name: tmp
              mountPath: /tmp
      containers:
        - name: route-emitter
          image: {{ .Values.routeEmitter.image.repository }}:{{ default .Chart.AppVersion .Values.routeEmitter.image.tag }}
          imagePullPolicy: {{ .Values.routeEmitter.image.imagePullPolicy }}
          args:
          - --config
          - /tmp/route-emitter.json
          volumeMounts:
            - name: route-emitter
              mountPath: /etc/ssl/certs/route-emitter
            - name: route-emitter-config
              mountPath: /route-emitter
            - name: tmp
              mountPath: /tmp
          {{- if .Values.routeEmitter.resources }}
          resources:
            {{- toYaml .Values.routeEmitter.resources | nindent 12 }}
          {{- end }}
      volumes:
        - name: tmp
          emptyDir: {}
        - name: route-emitter
          secret:
            secretName: {{ default "route-emitter" .Values.routeEmitter.certificateSecret }}
        - name: route-emitter-config
          configMap:
            name: route-emitter-configmap
      {{- if .Values.routeEmitter.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.routeEmitter.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.routeEmitter.tolerations }}
      tolerations:
        {{- toYaml .Values.routeEmitter.tolerations | nindent 8 }}
      {{- end }}
---
{{ if not .Values.routeEmitter.certificateSecret }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: route-emitter
spec:
  secretName: route-emitter
  commonName: route-emitter
  issuerRef:
    name: ca-issuer
    kind: ClusterIssuer
  usages:
    - key encipherment
    - digital signature
    - client auth
  privateKey:
    rotationPolicy: Always
{{end }}
{{- end }}