{{- if .Values.routeEmitter.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: route-emitter
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: route-emitter
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: route-emitter
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: route-emitter
subjects:
- kind: ServiceAccount
  name: route-emitter
  namespace: default
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: route-emitter-configmap
data:
  route-emitter.json: |-
    {
      "nats_addresses": "{{ .Values.routeEmitter.natsAddress }}",
      "nats_tls_enabled": true,
      "nats_ca_cert_file": "/etc/ssl/certs/route-emitter/ca.crt",
      "nats_client_cert_file": "/etc/ssl/certs/route-emitter/tls.crt",
      "nats_client_key_file": "/etc/ssl/certs/route-emitter/tls.key",
      "communication_timeout": "30s",
      "sync_interval": "60s",
      "debug_address": "127.0.0.1:17009",
      "log_level": "info",
      "lock_retry_interval": "5s",
      "lock_ttl": "15s",
      "healthcheck_address": "127.0.0.1:17011",
      "register_direct_instance_routes": false,
      "route_emitting_workers": 20,
      "tcp_route_ttl": "2m",
      "unregistration_interval": "30s",
      "unregistration_send_count": 20,
      "jitter_factor": 0.8,
      "time_format": "rfc3339",
      "locket_enabled": true,
      "locket_session_name": "route-emitter",
      "locket_address": "{{ .Values.routeEmitter.locketAddress }}",
      "uuid": "$NODE_UID",
      "locket_ca_cert_file": "/etc/ssl/certs/route-emitter/ca.crt",
      "locket_client_cert_file": "/etc/ssl/certs/route-emitter/tls.crt",
      "locket_client_key_file": "/etc/ssl/certs/route-emitter/tls.key",
      "bbs_ca_cert_file": "/etc/ssl/certs/route-emitter/ca.crt",
      "bbs_client_cert_file": "/etc/ssl/certs/route-emitter/tls.crt",
      "bbs_client_key_file": "/etc/ssl/certs/route-emitter/tls.key",
      "bbs_address": "{{ .Values.routeEmitter.bbsAddress }}",
      "cell_id": "$NODE_UID",
      "enable_internal_emitter": true,
      "enable_tcp_emitter": false,
      "tcp_enable_tls": true,
      "routing_api": {
          "url": "http://routing-api.service.cf.internal",
          "port": 3000,
          "auth_enabled": true
      },
      "loggregator": {
        "loggregator_use_v2_api": true,
        "loggregator_api_port": 3458,
        "loggregator_api_host": "forwarder-agent.{{ .Release.Namespace }}.svc.cluster.local",
        "loggregator_ca_path": "/etc/ssl/certs/route-emitter/ca.crt",
        "loggregator_cert_path": "/etc/ssl/certs/route-emitter/tls.crt",
        "loggregator_key_path": "/etc/ssl/certs/route-emitter/tls.key",
        "loggregator_job_deployment": "cf",
        "loggregator_job_name": "route-emitter",
        "loggregator_job_origin": "route-emitter",
        "loggregator_source_id": "route-emitter"
      }
    }
---
kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: route-emitter
  labels:
    app: route-emitter
spec:
  selector:
    matchLabels:
      app: route-emitter
  template:
    metadata:
      labels:
        app: route-emitter
    spec:
      serviceAccountName: route-emitter
      initContainers:
        - name: route-emitter-init
          image: bitnami/kubectl:latest
          imagePullPolicy: IfNotPresent
          command:
            - sh
            - -c
            - |
              NODE_UID=$(kubectl get node $NODE_NAME -o jsonpath='{.metadata.uid}')
              export NODE_UID
              cat /route-emitter/route-emitter.json | envsubst > /tmp/route-emitter.json
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: route-emitter-config
              mountPath: /route-emitter
            - name: tmp
              mountPath: /tmp
      containers:
        - name: route-emitter
          image: {{ .Values.routeEmitter.image.repository }}:{{ default .Chart.AppVersion .Values.routeEmitter.image.tag }}
          imagePullPolicy: {{ .Values.routeEmitter.image.imagePullPolicy }}
          imagePullPolicy: IfNotPresent
          args:
          - --config
          - /tmp/route-emitter.json
          volumeMounts:
            - name: route-emitter
              mountPath: /etc/ssl/certs/route-emitter
            - name: route-emitter-config
              mountPath: /route-emitter
            - name: tmp
              mountPath: /tmp
          {{- if .Values.routeEmitter.resources }}
          resources:
            {{- toYaml .Values.routeEmitter.resources | nindent 12 }}
          {{- end }}
      volumes:
        - name: tmp
          emptyDir: {}
        - name: route-emitter
          secret:
            secretName: {{ default "route-emitter" .Values.routeEmitter.certificateSecret }}
        - name: route-emitter-config
          configMap:
            name: route-emitter-configmap
      {{- if .Values.routeEmitter.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.routeEmitter.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.routeEmitter.tolerations }}
      tolerations:
        {{- toYaml .Values.routeEmitter.tolerations | nindent 8 }}
      {{- end }}
---
{{ if not .Values.routeEmitter.certificateSecret }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: route-emitter
spec:
  secretName: route-emitter
  commonName: route-emitter
  issuerRef:
    name: ca-issuer
    kind: ClusterIssuer
  usages:
    - key encipherment
    - digital signature
    - client auth
  privateKey:
    rotationPolicy: Always
{{end }}
{{- end }}