name: capi
version: 0.12.0
description: Helm chart for CF API components
type: application
apiVersion: v2
# renovate: dataSource=docker depName=capi-release packageName=ghcr.io/cloudfoundry/k8s/cloud-controller
appVersion: 1.225.0
