name: capi
version: 0.6.0
description: Helm chart for CF API components
type: application
apiVersion: v2
# renovate: depName=capi-release image=ghcr.io/cloudfoundry/k8s/cloud-controller
appVersion: 1.225.0
