ccDeploymentUpdater:
  nodeSelector: ~
  tolerations: ~

ccWorker:
  nodeSelector: ~
  tolerations: ~

ccUploader:
  certificateSecret: ~
  hostname: "cc-uploader.default.svc.cluster.local"
  image:
    repository: ghcr.io/cloudfoundry/k8s/cc-uploader
    tag: ~
    imagePullPolicy: IfNotPresent
  nodeSelector: ~
  tolerations: ~


ccWorkerClock:
  nodeSelector: ~
  tolerations: ~

cloudController:
  enabled: false
  certificateSecret: ~
  appDomain: apps.127-0-0-1.nip.io
  externalDomain: api.127-0-0-1.nip.io
  internalDomain: cloud-controller.default.svc.cluster.local
  internalServiceHostname: cloud-controller.default.svc.cluster.local
  systemDomain: system.127-0-0-1.nip.io
  appSSHEndpoint: ssh.127-0-0-1.nip.io:2222
  sshProxyKeyFingerprint: ~
  loginUrl: https://uaa.127-0-0-1.nip.io
  image:
    repository: ghcr.io/cloudfoundry/k8s/cloud-controller
    tag: ~
    imagePullPolicy: IfNotPresent
  doppler:
    url: wss://doppler.127-0-0-1.nip.io:443
  logCache:
    url: https://log-cache.127-0-0-1.nip.io
  logStream:
    url: https://log-stream.127-0-0-1.nip.io
  uaa:
    url: https://uaa.127-0-0-1.nip.io
  blobstore:
    resource_directory_key: cc-resources
    app_package_directory_key: cc-packages
    droplet_directory_key: cc-droplets
    buildpack_directory_key: cc-buildpacks
    fog_connection:
      provider: AWS
      endpoint:  http://blobstore.127-0-0-1.nip.io
      aws_access_key_id: admin
      aws_secret_access_key: ~
  diego:
    fileServerUrl: https://file-server.127-0-0-1.nip.io
    ccUploaderUrl: http://cc-uploader.default.svc.cluster.local:9090
  credhubApi:
    internalUrl: https://credhub.127-0-0-1.nip.io
    externalUrl: https://credhub.127-0-0-1.nip.io
  nats:
    address: nats.default.svc.cluster.local:4222
  nodeSelector: ~
  tolerations: ~

localWorker:
  image:
    repository: ghcr.io/cloudfoundry/k8s/cloud-controller
    tag: ~
    imagePullPolicy: IfNotPresent

routeRegistrar:
  image:
    repository: ghcr.io/cloudfoundry/k8s/route-registrar
    # renovate: dataSource=docker depName=routing-release packageName=ghcr.io/cloudfoundry/k8s/route-registrar
    tag: "0.364.0"
    imagePullPolicy: IfNotPresent

nginx:
  image:
    repository: ghcr.io/cloudfoundry/k8s/cc-nginx
    tag: ~
    imagePullPolicy: IfNotPresent

udpForwarder:
  image:
    repository: ghcr.io/cloudfoundry/k8s/udp-forwarder
    # renovate: dataSource=docker depName=loggregator-agent-release packageName=ghcr.io/cloudfoundry/k8s/udp-forwarder
    tag: "8.3.13"
    imagePullPolicy: IfNotPresent

tpsWatcher:
  enabled: false
  certificateSecret: ~
  hostname: tps.default.svc.cluster.local
  image:
    repository: ghcr.io/cloudfoundry/k8s/tps-watcher
    tag: ~
    imagePullPolicy: IfNotPresent
  nodeSelector: ~
  tolerations: ~

dbPassword: ~
oauthClientsSecret: ~
