name: log-cache
version: 0.7.0
description: Helm chart for Log Cache components
type: application
apiVersion: v2
# renovate: dataSource=docker depName=log-cache-release packageName=ghcr.io/cloudfoundry/k8s/gateway
appVersion: 3.2.4
