nfsbroker:
  enabled: true
  certificateSecret: ""
  oauthClientsSecret: ""
  credhubURL: https://credhub.default.svc.cluster.local:8844
  # NFS Broker credentials
  # If not provided, secure random values will be generated
  username: ~      # defaults to "nfsbroker" if not set
  password: ~      # 32-char random generated if not set
  image:
    repository: ghcr.io/cloudfoundry/k8s/nfsbroker
    tag: ""
    imagePullPolicy: IfNotPresent
  resources: {}
  nodeSelector: ~
  tolerations: ~


nfsv3driver:
  enabled: true
  image:
    repository: ghcr.io/cloudfoundry/k8s/nfsv3driver
    tag: ""
    imagePullPolicy: IfNotPresent
  nodeSelector:
    cloudfoundry.org/cell: "true"
  tolerations:
    - key: cloudfoundry.org/cell
      operator: Equal
      value: "true"
      effect: NoSchedule
